In [40]:
from bs4 import BeautifulSoup as bs
import requests
from datetime import datetime,timedelta
import pandas as pd
import numpy as np

In [37]:
tomorrow = datetime.now().replace(hour=0, minute=0, second=0, microsecond=0) + timedelta(days=1)
tomorrow_str = tomorrow.strftime('%d.%m.%Y')
URL = f"https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime={tomorrow_str}+00:00|UTC|DAY&biddingZone.values=CTY|10YFI-1--------U!BZN|10YFI-1--------U&resolution.values=PT60M&dateTime.timezone=UTC&dateTime.timezone_input=UTC"

with requests.get(URL) as r:
    soup = bs(r.content, "html.parser")

table = soup.tbody.text

In [43]:
rows = table.replace('\n\n','').replace(':00\n',':00,').splitlines()
data = []
for row in rows:
    data.append([tomorrow + timedelta(hours=int(row[:2])), row.split(',')[1]])
df = pd.DataFrame(data=data, columns=['datetime','price']).set_index('datetime')
df['price'] = df['price'].replace('-',np.nan).astype('float')
# datetime: Time in UTC
# price: Day-ahead price EUR/MWh
df

                     price
datetime
2022-10-09 00:00:00   2.01
2022-10-09 01:00:00   2.22
2022-10-09 02:00:00   4.52
2022-10-09 03:00:00   7.71
2022-10-09 04:00:00  10.10
2022-10-09 05:00:00  11.37
2022-10-09 06:00:00  13.94
2022-10-09 07:00:00  16.82
2022-10-09 08:00:00  17.15
2022-10-09 09:00:00  15.54
2022-10-09 10:00:00  14.67
2022-10-09 11:00:00  14.24
2022-10-09 12:00:00  14.51
2022-10-09 13:00:00  14.42
2022-10-09 14:00:00  14.68
2022-10-09 15:00:00  15.04
2022-10-09 16:00:00  15.44
2022-10-09 17:00:00  15.07
2022-10-09 18:00:00  14.29
2022-10-09 19:00:00  14.30
2022-10-09 20:00:00  12.71
2022-10-09 21:00:00  10.73
2022-10-09 22:00:00    NaN
2022-10-09 23:00:00    NaN